### ISSUE TITLE
Sensor does not seem to get data

### ISSUE THREAD

**Issue by Carlbrander** [ThomasPrior/EthermineInfo#1]
Hey, it's me from the home assistant forum. I collected the following logs:

Logger: homeassistant.helpers.entity
Source: custom_components/ethermineinfo/sensor.py:124
Integration: ethermineinfo (documentation, issues)
First occurred: 23:16:10 (1 occurrences)
Last logged: 23:16:10

Update for sensor.ethermineinfo_83984_____________________________________________113 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 524, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 280, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/ethermineinfo/sensor.py", line 124, in _update
    self._state = r.json()['data']['currentStatistics']['activeWorkers']
KeyError: 'data'

I hope this will help solving the problem.

Greetings,

**Comment by ThomasPrior** [comment]
From my testing I only get “unknown” if I don’t use a valid miner address.

Use https://api.ethermine.org/miner/miner_address_here/dashboard - this should tell you if you have used the correct address. A correct address will return data, an incorrect address will return {"status":"ERROR","error":"Invalid address"}.

My logs with an incorrect miner address match yours:

```
Update for sensor.ethermineinfo_REDACTED fails

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 292, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 490, in async_device_update
    raise exc
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/util/__init__.py", line 278, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/ethermineinfo/sensor.py", line 124, in _update
    self._state = r.json()['data']['currentStatistics']['activeWorkers']
KeyError: 'data'
```

**Comment by Carlbrander** [comment]
Thanks for helping me!

I checked my adress and it is correct and returning data...
in my configuration.YAML i implemented the following:

sensor:
  - platform: ethermineinfo
    miner_address: 0x_____________________________________9
    currency_name: CHF

What else could make it not work?

Thanks in advance.

**Comment by ThomasPrior** [comment]
Could you remove the 0x at the front and let me know if that changes the behaviour in any way?

**Comment by Carlbrander** [comment]
Yes, I removed the 0x and now it works! 
Thank you so much for helping and designing this integration in the first place!

**Comment by Crazyscorpio88** [comment]
Hello,

It seems that I have the same Issue or at least same symptoms : 
```
Logger: homeassistant.helpers.entity
Source: custom_components/ethermineinfo/sensor.py:192
Integration: ethermineinfo (documentation, issues)
First occurred: 19:18:10 (1 occurrences)
Last logged: 19:18:10

Update for sensor.ethermineinfo_2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx7 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/ethermineinfo/sensor.py", line 192, in _update
    self._state = r.json()['data']['currentStatistics']['activeWorkers']
KeyError: 'activeWorkers'
```

Same issue if i type with 0x in front of my miner address.

Version installed : 1.0.1
Core : core-2021.9.4
OS : Home Assistant OS 6.3

When I go on API : 
`{"status":"OK","data":{"statistics":[],"workers":[],"currentStatistics":{},"settings":{"monitor":0,"minPayout":1000000000000000000,"email":""}}}`

**Comment by ThomasPrior** [comment]
Can you post the relevant extract of your configuration.yaml please?

**Comment by Crazyscorpio88** [comment]
Of course

```
sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: processor_temperature
      - type: memory_free
      - type: memory_use
      - type: memory_use_percent
      - type: disk_use_percent
        arg: /
      - type: disk_use
      - type: disk_free
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
        
  - platform: ethermineinfo
    miner_address: "0x2xxxxxxxxxxxxxxxxxxxx7"
    currency_name: EUR

```
EDIT: As discussed I wasn't working on the good minerpool

**Comment by ThomasPrior** [comment]
Without the complete address there's not a lot to check I'm afraid.

If you have an account, you can pop over to the HomeAssistant forums and
send me a PM, or you can spin up a temporary address and run on that whilst
we test.

**Comment by Crazyscorpio88** [comment]
0x2a01a3c46a9cfe90e23e68ac33e163b6e9be3d27

**Comment by ThomasPrior** [comment]
You have no active workers, past or present on that address. There's no
data to be returned.

**Comment by Crazyscorpio88** [comment]
You are right... Damn boy, sorry for that ^^'

**Comment by ThomasPrior** [comment]
No worries, things like this happen to me too. If you have any other issues
don't hesitate to get in touch.
